[buf]
disabled = true

[character]
error_symbol = "[󰘧](bold red)"
success_symbol = "[󰘧](bold green)"

[directory]
truncate_to_repo = false

[dotnet]
detect_files = ["global.json", "Directory.Build.props", "Directory.Build.targets", "Packages.props"]

[git_branch]
symbol = " "
truncation_length = 18

[golang]
symbol = " "

[lua]
symbol = " "

[nix_shell]
symbol = " "

[package]
disabled = true
